/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AnalizadorLexico;

import AST.*;
import TablaSimbolos.*;
import Generador.GeneradorAssembly;
import Generador.Generador;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author tavto
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    private NodoPrograma raizAST;
    
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnalizar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAnalizar5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAnalizarSem1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnGenerarAssembly = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalizarLex = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAST = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalizarSin = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTablaSimbolos = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAnalizarSem = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtCodigo3DC = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtCodigoAssembly = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnAnalizar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAnalizar2.setText("Analizar");
        btnAnalizar2.setActionCommand("Analizar2");
        btnAnalizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizar2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Analizador Léxico");
        jLabel2.setAlignmentX(0.5F);

        btnAnalizar5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAnalizar5.setText("Limpiar");
        btnAnalizar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizar5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Analizador Semántico");
        jLabel7.setAlignmentX(0.5F);

        txtAnalizarSem1.setEditable(false);
        txtAnalizarSem1.setColumns(20);
        txtAnalizarSem1.setRows(5);
        jScrollPane7.setViewportView(txtAnalizarSem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArchivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnArchivo.setText("Abrir Archivo");
        btnArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnGenerarAssembly.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGenerarAssembly.setText("Compilar");
        btnGenerarAssembly.setActionCommand("Analizar2");
        btnGenerarAssembly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarAssemblyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarAssembly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnArchivo)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGenerarAssembly)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("IDE", jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Analizador Léxico");
        jLabel1.setAlignmentX(0.5F);

        txtAnalizarLex.setEditable(false);
        txtAnalizarLex.setColumns(20);
        txtAnalizarLex.setRows(5);
        jScrollPane2.setViewportView(txtAnalizarLex);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(629, 629, 629))
        );

        jTabbedPane1.addTab("Análisis Léxico", jPanel5);

        txtAST.setEditable(false);
        txtAST.setColumns(20);
        txtAST.setRows(5);
        jScrollPane5.setViewportView(txtAST);

        txtAnalizarSin.setEditable(false);
        txtAnalizarSin.setColumns(20);
        txtAnalizarSin.setRows(5);
        jScrollPane3.setViewportView(txtAnalizarSin);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AST");
        jLabel10.setAlignmentX(0.5F);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Analizador Sintáctico");
        jLabel11.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(613, 613, 613))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jLabel11)
                    .addContainerGap(1101, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Análisis Sintáctico", jPanel6);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Analizador Semántico");
        jLabel6.setAlignmentX(0.5F);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tabla de Símbolos");
        jLabel5.setAlignmentX(0.5F);

        txtTablaSimbolos.setEditable(false);
        txtTablaSimbolos.setColumns(20);
        txtTablaSimbolos.setRows(5);
        jScrollPane4.setViewportView(txtTablaSimbolos);

        txtAnalizarSem.setEditable(false);
        txtAnalizarSem.setColumns(20);
        txtAnalizarSem.setRows(5);
        jScrollPane6.setViewportView(txtAnalizarSem);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Análisis semántico", jPanel7);

        txtCodigo3DC.setEditable(false);
        txtCodigo3DC.setColumns(20);
        txtCodigo3DC.setRows(5);
        jScrollPane9.setViewportView(txtCodigo3DC);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Código Intermedio 3DC");
        jLabel8.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Código en 3DC", jPanel8);

        txtCodigoAssembly.setEditable(false);
        txtCodigoAssembly.setColumns(20);
        txtCodigoAssembly.setRows(5);
        jScrollPane8.setViewportView(txtCodigoAssembly);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Código Assembly");
        jLabel9.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Código en Assembly", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   private boolean analizarLexico() throws IOException { //analisis Léxico usando el primer lexer que creamos
        int cont = 1; //Número de línea
        String expr = (String) txtResultado.getText(); //Obtengo el texto en pantalla
        Lexer lexer = new Lexer(new StringReader(expr)); //Crea instancia del analizador léxico Lexer.java y le pasa el código fuente convertido en un flujo de lectura
        //Este lexer devuelve los Enum que yo cree, es un poco más estético que el otro por eso hay 2 pero tienen los mismos tokens
        String resultado = "LINEA " + cont + "\t\tSimbolo\n\n"; //Resultado es lo que se muestra en pantalla
        boolean hayErrores = false; //Funciona de bandera para saber si se encontró un símbolo inválido durante el proceso
        
        try {
            while (true) { //lee token por token hasta que termine el archivo
                Tokens token = lexer.yylex();
                if (token == null) { //Cuando se acabe el archivo
                    txtAnalizarLex.setText(resultado); //muestra en pantalla
                    return !hayErrores; //retorna true si no hubo errores 
                }
                switch (token) { //Va completando el resultado
                    case Linea:
                        cont++;
                        resultado += "LINEA " + cont + "\n\n";
                        break;
                    case ERROR:
                        resultado += "\t\t ERROR: Simbolo no definido\n";
                        hayErrores = true;
                        break;
                    default:
                        resultado += "\t\t" + lexer.lexeme + " -> Token: " + token + "\n";
                        break;
                }
            }
        } catch (IOException ex) {
            txtAnalizarLex.setText("Error grave al analizar el léxico: " + ex.getMessage()); //si hay algún error lo muestra acá
            return false;
        }
    }
   //Oportunidad de mejora de eficiencia, también usar StringBuilder como en los otros casos, aun así funciona para mostrar  
   
   
    private void mostrarArbolAST(NodoPrograma raiz) {
        if (raiz == null) { //Si no hay arbol, no hay nada que mostrar
            return;
        }
        //llama al método imprimir del arbol y le pasa la identación (inicia sin nada) y lo guarda en una variable para mostrarlo en pantalla luego
        String arbolString = raiz.imprimir(""); 
        txtAST.setText(arbolString);
    }
    
    private boolean analizarSintactico() {
        String ST = txtResultado.getText(); //obtiene el contenido del "IDE"
        ST = ST.trim(); //quita los espacios del inicio y final para evitar errores "EOF"

        Sintax s = new Sintax(new AnalizadorLexico.LexerCup(new StringReader(ST))); //instancia un Lexer que le devuelve los símbolos para usar en el análisis sintáctico 
        //Este lexer es otro al que usamos  en el analisisLexico 
        try {
            java_cup.runtime.Symbol rootSymbol = s.parse(); //Acá el parser pide todos los tokens uno a uno y valida la gramatica y va ejecutando las acciones para crear el AST
            //rootSymbol es el resultado final de eso. y en su atributo value va lo que devuelve la regla INICIO del Sintax.cup (o sea el nodo programa)

            if (rootSymbol.value instanceof NodoPrograma) { //Acá comprueba que sea una instancia válida de AST
                this.raizAST = (NodoPrograma) rootSymbol.value; //Guarda el árbol generado en una variable global de la clase para usarla en otros lados

                txtAnalizarSin.setText("Análisis Sintáctico realizado correctamente."); //avisa que salió todo bien
                txtAnalizarSin.setForeground(new Color(25, 111, 61)); 

                
                mostrarArbolAST(this.raizAST);  //llama al método para mostrar el AST

                return true; //avisa que salió todo bien al método de compilación
            } else {
                txtAnalizarSin.setText("Error: No se pudo construir el árbol sintáctico."); //si el AST creado no es válido, muestra el error y devuelve false terminando el proceso de compilación
                txtAnalizarSin.setForeground(Color.red);
                return false;
            }

        } catch (Exception ex) { //si el código está mal escrito entramos acá
            Symbol sym = s.getS(); //recupera el simbolo del problema
            txtAnalizarSin.setForeground(Color.red);
            if (sym != null) { //si sabemos donde es el problema lo avisamos de forma específica
                txtAnalizarSin.setText("Error de Sintaxis. Línea: " + (sym.right + 1) + " Caracter: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            } else {//si desconocemos el problema damos un mensaje general 
                txtAnalizarSin.setText("Error de Sintaxis catastrófico (posiblemente caracteres al final del archivo)");
            }
            return false;
        }
    }
    
    private void mostrarTablaSimbolos(TablaSimbolos ts) {
        if (ts == null) { //si no hay tabla
            return;
        }
        String tablaString = ts.imprimir(); //llamamos al método imprimir de la tabla y luego la mostramos en pantalla
        txtTablaSimbolos.setText(tablaString); 
    }
    
    private boolean analizarSemantico() {
        if (this.raizAST == null) { //necesita un AST para hacer el analisis
            txtAnalizarSem.setText("No se puede realizar análisis semántico sin un AST válido.");
            return false;
        }

        TablaSimbolos ts = new TablaSimbolos(); //instancia una tabla de simbolos

        try {
            //Ejecutar el análisis semántico mediante el AST en forma de cascada
            this.raizAST.analizar(ts);

            //Si no hubo error en lo anterior decimos que es un éxito
            txtAnalizarSem.setText("Análisis Semántico realizado correctamente.");
            txtAnalizarSem.setForeground(new Color(25, 111, 61)); // Verde

            mostrarTablaSimbolos(ts); //llamamos a la función para mostrar la tabla de símbolos

            return true;

        } catch (ExcepcionSemantica ex) {
            txtAnalizarSem.setText("Error Semántico: " + ex.getMessage()); //si hubo una excepción la avisamos por pantalla
            txtAnalizarSem.setForeground(Color.red);
            return false;
        }
    }
    
    private void generar3DC() {
        if (this.raizAST == null){ //si el AST no existe, no hay nada que hacer acá
            return;
        }
        String codigo = (String) this.raizAST.generarCodigo(); //esto va a iniciar la cascada de generación de código 3DC
        txtCodigo3DC.setText(codigo); //mostramos lo que se generó en pantalla
    }
    
    private void generarAssembly() {
        //Traemos el código 3DC generado previamente
        String codigo3DC = txtCodigo3DC.getText();
        
        if (codigo3DC == null || codigo3DC.trim().isEmpty()) {
            txtCodigoAssembly.setText("No hay código 3DC para traducir.");
            return;
        }

        //Instanciamos su traductor
        GeneradorAssembly genAsm = new GeneradorAssembly();
        String codigoAsm = genAsm.generar(codigo3DC); //le pedimos que lo traduzca
        
        txtCodigoAssembly.setText(codigoAsm); //mostramos la traducción en pantalla
    }
    
    private void compilar() throws IOException {
        limpiarPantallas(); //Borra los resultados visibles de la anterior compilación
    
        if (!analizarLexico()) { //llama al método para el análisis léxico en caso de error  se muestra esto en pantalla y se finaliza el proceso de compilación
            txtAnalizarLex.append("\n Se ha encontrado un error en este proceso, se ha detenido el proceso de compilación");
            return;
        }
        
        if (!analizarSintactico()) { //llama al método para el análisis sintactico en caso de error  se muestra esto en pantalla (también en el Ast) y se finaliza el proceso de compilación
            txtAnalizarSin.append("\n Se ha encontrado un error en este proceso, se ha detenido el proceso de compilación");
            txtAST.append("\n Se ha encontrado un error en este proceso, se ha detenido el proceso de compilación");
            return; // Detenerse si la sintaxis falla (no hay AST)
        }
        
        if (!analizarSemantico()) {//llama al método para el análisis Semántico en caso de error  se muestra esto en pantalla y se finaliza el proceso de compilación
            txtAnalizarSem.append("\n Se ha encontrado un error en este proceso, se ha detenido el proceso de compilación");
            txtTablaSimbolos.append("\n Se ha encontrado un error en este proceso, se ha detenido el proceso de compilación");
            return; // Detenerse si la sintaxis falla (no hay AST)
        }
        generar3DC(); //si pasaron los análisis entonces se debe poder generar el código 3DC
        
        if (!txtCodigo3DC.getText().isEmpty() && !txtCodigo3DC.getText().startsWith("Error")) { //si el código 3DC está vacio o empieza con error este paso se saltea
            generarAssembly();
            System.out.println("Compilación realizada exitosamente");
        }
}
    
    private void limpiarPantallas() { //Todos los cuadros de texto no editables se vacían con este método (solo no afecta al que actua de IDE)
        txtAnalizarLex.setText(null);
        txtAnalizarSin.setText(null);
        txtAnalizarSem.setText(null);
        txtAST.setText(null);
        txtTablaSimbolos.setText(null);
        txtCodigo3DC.setText(null);
        txtCodigoAssembly.setText(null);
    }
    
    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // Este boton permite seleccionar un archivo y copia su contenido en un cuadro de texto llamado txtResultado
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
        try {
            String  ST = new String(Files.readAllBytes(archivo.toPath()));
            txtResultado.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnAnalizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizar2ActionPerformed

    private void btnAnalizar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizar5ActionPerformed

    private void btnGenerarAssemblyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAssemblyActionPerformed
        try {
            compilar(); //llama a nuestro método compilar
                    } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarAssemblyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar2;
    private javax.swing.JButton btnAnalizar5;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnGenerarAssembly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtAST;
    private javax.swing.JTextArea txtAnalizarLex;
    private javax.swing.JTextArea txtAnalizarSem;
    private javax.swing.JTextArea txtAnalizarSem1;
    private javax.swing.JTextArea txtAnalizarSin;
    private javax.swing.JTextArea txtCodigo3DC;
    private javax.swing.JTextArea txtCodigoAssembly;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtTablaSimbolos;
    // End of variables declaration//GEN-END:variables
}
