
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 28 02:09:10 ART 2025
//----------------------------------------------------

package AnalizadorLexico;

import java_cup.runtime.Symbol;
import java.util.List;
import java.util.ArrayList;
import AST.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Nov 28 02:09:10 ART 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\052\000\002\002\004\000\002\002\011\000\002\002" +
    "\011\000\002\002\011\000\002\003\002\000\002\003\004" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\011\010\000\002" +
    "\011\012\000\002\012\007\000\002\013\005\000\002\005" +
    "\006\000\002\005\010\000\002\005\006\000\002\005\010" +
    "\000\002\005\005\000\002\005\007\000\002\005\005\000" +
    "\002\005\007\000\002\006\006\000\002\007\005\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\005\000\002\010\005\000\002\010\005" +
    "\000\002\010\005\000\002\010\005\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\004\000\002\010\004\000\002\010" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\010\004\006\005\007\006\004\001\002\000" +
    "\004\007\152\001\002\000\004\002\151\001\002\000\004" +
    "\007\143\001\002\000\004\007\010\001\002\000\004\020" +
    "\011\001\002\000\004\021\012\001\002\000\004\023\013" +
    "\001\002\000\022\004\ufffd\005\ufffd\010\ufffd\024\ufffd\025" +
    "\ufffd\027\ufffd\032\ufffd\042\ufffd\001\002\000\022\004\024" +
    "\005\025\010\017\024\016\025\027\027\020\032\021\042" +
    "\032\001\002\000\022\004\ufff7\005\ufff7\010\ufff7\024\ufff7" +
    "\025\ufff7\027\ufff7\032\ufff7\042\ufff7\001\002\000\004\002" +
    "\ufffe\001\002\000\020\011\045\012\041\015\043\020\046" +
    "\025\047\026\040\035\042\001\002\000\004\020\132\001" +
    "\002\000\004\020\123\001\002\000\022\004\ufffb\005\ufffb" +
    "\010\ufffb\024\ufffb\025\ufffb\027\ufffb\032\ufffb\042\ufffb\001" +
    "\002\000\022\004\ufffc\005\ufffc\010\ufffc\024\ufffc\025\ufffc" +
    "\027\ufffc\032\ufffc\042\ufffc\001\002\000\004\025\116\001" +
    "\002\000\004\025\111\001\002\000\022\004\ufffa\005\ufffa" +
    "\010\ufffa\024\ufffa\025\ufffa\027\ufffa\032\ufffa\042\ufffa\001" +
    "\002\000\004\013\106\001\002\000\022\004\ufff8\005\ufff8" +
    "\010\ufff8\024\ufff8\025\ufff8\027\ufff8\032\ufff8\042\ufff8\001" +
    "\002\000\022\004\ufff9\005\ufff9\010\ufff9\024\ufff9\025\ufff9" +
    "\027\ufff9\032\ufff9\042\ufff9\001\002\000\006\004\033\005" +
    "\034\001\002\000\004\025\101\001\002\000\004\025\035" +
    "\001\002\000\006\013\037\022\036\001\002\000\022\004" +
    "\ufff0\005\ufff0\010\ufff0\024\ufff0\025\ufff0\027\ufff0\032\ufff0" +
    "\042\ufff0\001\002\000\020\011\045\012\041\015\043\020" +
    "\046\025\047\026\040\035\042\001\002\000\032\014\uffe8" +
    "\015\uffe8\016\uffe8\017\uffe8\021\uffe8\022\uffe8\033\uffe8\034" +
    "\uffe8\036\uffe8\037\uffe8\040\uffe8\041\uffe8\001\002\000\032" +
    "\014\uffe5\015\uffe5\016\uffe5\017\uffe5\021\uffe5\022\uffe5\033" +
    "\uffe5\034\uffe5\036\uffe5\037\uffe5\040\uffe5\041\uffe5\001\002" +
    "\000\020\011\045\012\041\015\043\020\046\025\047\026" +
    "\040\035\042\001\002\000\020\011\045\012\041\015\043" +
    "\020\046\025\047\026\040\035\042\001\002\000\030\014" +
    "\057\015\062\016\051\017\054\022\076\033\055\034\056" +
    "\036\060\037\053\040\052\041\063\001\002\000\032\014" +
    "\uffe6\015\uffe6\016\uffe6\017\uffe6\021\uffe6\022\uffe6\033\uffe6" +
    "\034\uffe6\036\uffe6\037\uffe6\040\uffe6\041\uffe6\001\002\000" +
    "\020\011\045\012\041\015\043\020\046\025\047\026\040" +
    "\035\042\001\002\000\032\014\uffe7\015\uffe7\016\uffe7\017" +
    "\uffe7\021\uffe7\022\uffe7\033\uffe7\034\uffe7\036\uffe7\037\uffe7" +
    "\040\uffe7\041\uffe7\001\002\000\030\014\057\015\062\016" +
    "\051\017\054\021\061\033\055\034\056\036\060\037\053" +
    "\040\052\041\063\001\002\000\020\011\045\012\041\015" +
    "\043\020\046\025\047\026\040\035\042\001\002\000\020" +
    "\011\045\012\041\015\043\020\046\025\047\026\040\035" +
    "\042\001\002\000\020\011\045\012\041\015\043\020\046" +
    "\025\047\026\040\035\042\001\002\000\020\011\045\012" +
    "\041\015\043\020\046\025\047\026\040\035\042\001\002" +
    "\000\020\011\045\012\041\015\043\020\046\025\047\026" +
    "\040\035\042\001\002\000\020\011\045\012\041\015\043" +
    "\020\046\025\047\026\040\035\042\001\002\000\020\011" +
    "\045\012\041\015\043\020\046\025\047\026\040\035\042" +
    "\001\002\000\020\011\045\012\041\015\043\020\046\025" +
    "\047\026\040\035\042\001\002\000\032\014\uffd8\015\uffd8" +
    "\016\uffd8\017\uffd8\021\uffd8\022\uffd8\033\uffd8\034\uffd8\036" +
    "\uffd8\037\uffd8\040\uffd8\041\uffd8\001\002\000\020\011\045" +
    "\012\041\015\043\020\046\025\047\026\040\035\042\001" +
    "\002\000\020\011\045\012\041\015\043\020\046\025\047" +
    "\026\040\035\042\001\002\000\032\014\uffe0\015\uffe0\016" +
    "\uffe0\017\uffe0\021\uffe0\022\uffe0\033\uffe0\034\uffe0\036\uffe0" +
    "\037\uffe0\040\uffe0\041\uffe0\001\002\000\032\014\uffe3\015" +
    "\uffe3\016\051\017\054\021\uffe3\022\uffe3\033\uffe3\034\uffe3" +
    "\036\uffe3\037\uffe3\040\uffe3\041\063\001\002\000\032\014" +
    "\057\015\062\016\051\017\054\021\uffdd\022\uffdd\033\uffdd" +
    "\034\uffdd\036\uffdd\037\uffdd\040\uffdd\041\063\001\002\000" +
    "\032\014\uffe4\015\uffe4\016\051\017\054\021\uffe4\022\uffe4" +
    "\033\uffe4\034\uffe4\036\uffe4\037\uffe4\040\uffe4\041\063\001" +
    "\002\000\032\014\057\015\062\016\051\017\054\021\uffde" +
    "\022\uffde\033\055\034\uffde\036\060\037\053\040\052\041" +
    "\063\001\002\000\032\014\057\015\062\016\051\017\054" +
    "\021\uffdf\022\uffdf\033\uffdf\034\uffdf\036\060\037\053\040" +
    "\052\041\063\001\002\000\032\014\uffe1\015\uffe1\016\uffe1" +
    "\017\uffe1\021\uffe1\022\uffe1\033\uffe1\034\uffe1\036\uffe1\037" +
    "\uffe1\040\uffe1\041\uffe1\001\002\000\032\014\057\015\062" +
    "\016\051\017\054\021\uffdc\022\uffdc\033\uffdc\034\uffdc\036" +
    "\uffdc\037\uffdc\040\uffdc\041\063\001\002\000\032\014\057" +
    "\015\062\016\051\017\054\021\uffdb\022\uffdb\033\uffdb\034" +
    "\uffdb\036\060\037\053\040\uffdb\041\063\001\002\000\032" +
    "\014\uffe2\015\uffe2\016\uffe2\017\uffe2\021\uffe2\022\uffe2\033" +
    "\uffe2\034\uffe2\036\uffe2\037\uffe2\040\uffe2\041\uffe2\001\002" +
    "\000\022\004\uffef\005\uffef\010\uffef\024\uffef\025\uffef\027" +
    "\uffef\032\uffef\042\uffef\001\002\000\032\014\uffd9\015\uffd9" +
    "\016\uffd9\017\uffd9\021\uffd9\022\uffd9\033\uffd9\034\uffd9\036" +
    "\uffd9\037\uffd9\040\uffd9\041\uffd9\001\002\000\032\014\uffda" +
    "\015\uffda\016\uffda\017\uffda\021\uffda\022\uffda\033\uffda\034" +
    "\uffda\036\uffda\037\uffda\040\uffda\041\uffda\001\002\000\006" +
    "\013\103\022\102\001\002\000\022\004\ufff2\005\ufff2\010" +
    "\ufff2\024\ufff2\025\ufff2\027\ufff2\032\ufff2\042\ufff2\001\002" +
    "\000\020\011\045\012\041\015\043\020\046\025\047\026" +
    "\040\035\042\001\002\000\030\014\057\015\062\016\051" +
    "\017\054\022\105\033\055\034\056\036\060\037\053\040" +
    "\052\041\063\001\002\000\022\004\ufff1\005\ufff1\010\ufff1" +
    "\024\ufff1\025\ufff1\027\ufff1\032\ufff1\042\ufff1\001\002\000" +
    "\020\011\045\012\041\015\043\020\046\025\047\026\040" +
    "\035\042\001\002\000\030\014\057\015\062\016\051\017" +
    "\054\022\110\033\055\034\056\036\060\037\053\040\052" +
    "\041\063\001\002\000\022\004\uffea\005\uffea\010\uffea\024" +
    "\uffea\025\uffea\027\uffea\032\uffea\042\uffea\001\002\000\006" +
    "\013\113\022\112\001\002\000\022\004\uffec\005\uffec\010" +
    "\uffec\024\uffec\025\uffec\027\uffec\032\uffec\042\uffec\001\002" +
    "\000\020\011\045\012\041\015\043\020\046\025\047\026" +
    "\040\035\042\001\002\000\030\014\057\015\062\016\051" +
    "\017\054\022\115\033\055\034\056\036\060\037\053\040" +
    "\052\041\063\001\002\000\022\004\uffeb\005\uffeb\010\uffeb" +
    "\024\uffeb\025\uffeb\027\uffeb\032\uffeb\042\uffeb\001\002\000" +
    "\006\013\120\022\117\001\002\000\022\004\uffee\005\uffee" +
    "\010\uffee\024\uffee\025\uffee\027\uffee\032\uffee\042\uffee\001" +
    "\002\000\020\011\045\012\041\015\043\020\046\025\047" +
    "\026\040\035\042\001\002\000\030\014\057\015\062\016" +
    "\051\017\054\022\122\033\055\034\056\036\060\037\053" +
    "\040\052\041\063\001\002\000\022\004\uffed\005\uffed\010" +
    "\uffed\024\uffed\025\uffed\027\uffed\032\uffed\042\uffed\001\002" +
    "\000\020\011\045\012\041\015\043\020\046\025\047\026" +
    "\040\035\042\001\002\000\030\014\057\015\062\016\051" +
    "\017\054\021\125\033\055\034\056\036\060\037\053\040" +
    "\052\041\063\001\002\000\004\023\126\001\002\000\022" +
    "\004\ufffd\005\ufffd\010\ufffd\024\ufffd\025\ufffd\027\ufffd\032" +
    "\ufffd\042\ufffd\001\002\000\022\004\ufff4\005\ufff4\010\ufff4" +
    "\024\ufff4\025\ufff4\027\ufff4\032\ufff4\042\ufff4\001\002\000" +
    "\022\004\024\005\025\010\017\024\131\025\027\027\020" +
    "\032\021\042\032\001\002\000\024\004\ufff3\005\ufff3\010" +
    "\ufff3\024\ufff3\025\ufff3\027\ufff3\031\ufff3\032\ufff3\042\ufff3" +
    "\001\002\000\020\011\045\012\041\015\043\020\046\025" +
    "\047\026\040\035\042\001\002\000\030\014\057\015\062" +
    "\016\051\017\054\021\134\033\055\034\056\036\060\037" +
    "\053\040\052\041\063\001\002\000\004\030\135\001\002" +
    "\000\004\023\126\001\002\000\024\004\ufff6\005\ufff6\010" +
    "\ufff6\024\ufff6\025\ufff6\027\ufff6\031\137\032\ufff6\042\ufff6" +
    "\001\002\000\004\023\126\001\002\000\022\004\ufff5\005" +
    "\ufff5\010\ufff5\024\ufff5\025\ufff5\027\ufff5\032\ufff5\042\ufff5" +
    "\001\002\000\030\014\057\015\062\016\051\017\054\022" +
    "\142\033\055\034\056\036\060\037\053\040\052\041\063" +
    "\001\002\000\022\004\uffe9\005\uffe9\010\uffe9\024\uffe9\025" +
    "\uffe9\027\uffe9\032\uffe9\042\uffe9\001\002\000\004\020\144" +
    "\001\002\000\004\021\145\001\002\000\004\023\146\001" +
    "\002\000\022\004\ufffd\005\ufffd\010\ufffd\024\ufffd\025\ufffd" +
    "\027\ufffd\032\ufffd\042\ufffd\001\002\000\022\004\024\005" +
    "\025\010\017\024\150\025\027\027\020\032\021\042\032" +
    "\001\002\000\004\002\000\001\002\000\004\002\001\001" +
    "\002\000\004\020\153\001\002\000\004\021\154\001\002" +
    "\000\004\023\155\001\002\000\022\004\ufffd\005\ufffd\010" +
    "\ufffd\024\ufffd\025\ufffd\027\ufffd\032\ufffd\042\ufffd\001\002" +
    "\000\022\004\024\005\025\010\017\024\157\025\027\027" +
    "\020\032\021\042\032\001\002\000\004\002\uffff\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\013\001\001\000\016\004\022\005\021\006\025\007\030" +
    "\011\027\012\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\140\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\043\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\077\001\001\000\004\010\076" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\074\001\001\000\004\010\073\001\001\000\004\010" +
    "\072\001\001\000\004\010\071\001\001\000\004\010\070" +
    "\001\001\000\004\010\067\001\001\000\004\010\066\001" +
    "\001\000\004\010\065\001\001\000\002\001\001\000\004" +
    "\010\064\001\001\000\004\010\063\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\103\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\113\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\120\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\123\001\001\000\002\001\001\000\004\013\126" +
    "\001\001\000\004\003\127\001\001\000\002\001\001\000" +
    "\016\004\022\005\021\006\025\007\030\011\027\012\014" +
    "\001\001\000\002\001\001\000\004\010\132\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\013\135\001\001" +
    "\000\002\001\001\000\004\013\137\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\003\146\001" +
    "\001\000\016\004\022\005\021\006\025\007\030\011\027" +
    "\012\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\155\001\001\000\016\004\022\005\021\006\025\007" +
    "\030\011\027\012\014\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // EXPRESION ::= ParentesisAbre EXPRESION ParentesisCierra 
            {
              NodoAST RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST exp = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 RESULT = exp; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // EXPRESION ::= Resta EXPRESION 
            {
              NodoAST RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionUnaria(op.toString(), e); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // EXPRESION ::= Not EXPRESION 
            {
              NodoAST RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST e = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionUnaria(op.toString(), e); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= EXPRESION IgualIgual EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // EXPRESION ::= EXPRESION Menor EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // EXPRESION ::= EXPRESION Mayor EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXPRESION ::= EXPRESION Or EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXPRESION ::= EXPRESION And EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // EXPRESION ::= EXPRESION Modulo EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // EXPRESION ::= EXPRESION Division EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESION ::= EXPRESION Multiplicacion EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION ::= EXPRESION Resta EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESION ::= EXPRESION Suma EXPRESION 
            {
              NodoAST RESULT =null;
		int op1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST op1 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST op2 = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoOperacionBinaria(op1, op.toString(), op2); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXPRESION ::= False 
            {
              NodoAST RESULT =null;
		int valorleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object valor = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoLiteral(valor.toString()); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESION ::= True 
            {
              NodoAST RESULT =null;
		int valorleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object valor = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoLiteral(valor.toString()); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXPRESION ::= Identificador 
            {
              NodoAST RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoIdentificador(id.toString()); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXPRESION ::= Numero 
            {
              NodoAST RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object num = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoLiteral(num.toString()); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // RETORNO ::= Return EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
            RESULT = new NodoRetorno((NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("RETORNO",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ASIGNACION ::= Identificador Igual EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
            // CORREGIDO: id.toString()
            RESULT = new NodoAsignacion(id.toString(), (NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ASIGNACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DECLARACION ::= Bool Identificador Igual EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), (NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARACION ::= Bool Identificador PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), null);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION ::= Int Identificador Igual EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), (NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION ::= Int Identificador PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), null);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARACION ::= Var Bool Identificador Igual EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), (NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECLARACION ::= Var Bool Identificador PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), null);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DECLARACION ::= Var Int Identificador Igual EXPRESION PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoAST expresion = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), (NodoAST)expresion);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // DECLARACION ::= Var Int Identificador PuntoYComa 
            {
              NodoAST RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object tipo = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            RESULT = new NodoDeclaracion(tipo.toString(), id.toString(), null);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // BLOQUE ::= LlaveAbre LISTA_SENTENCIAS LlaveCierra 
            {
              NodoAST RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		List<NodoAST> lista = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 RESULT = new NodoBloque(lista); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("BLOQUE",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // WHILE_SENTENCIA ::= While ParentesisAbre EXPRESION ParentesisCierra BLOQUE 
            {
              NodoAST RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST cond = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int bloqueleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int bloqueright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST bloque = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoWhile(cond, bloque); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("WHILE_SENTENCIA",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // IF_SENTENCIA ::= If ParentesisAbre EXPRESION ParentesisCierra Then BLOQUE Else BLOQUE 
            {
              NodoAST RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).right;
		NodoAST cond = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).value;
		int bThenleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int bThenright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		NodoAST bThen = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int bElseleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int bElseright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST bElse = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoIf((NodoAST)cond, (NodoAST)bThen, (NodoAST)bElse); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // IF_SENTENCIA ::= If ParentesisAbre EXPRESION ParentesisCierra Then BLOQUE 
            {
              NodoAST RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		NodoAST cond = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int bThenleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int bThenright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST bThen = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = new NodoIf((NodoAST)cond, (NodoAST)bThen, null); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= WHILE_SENTENCIA 
            {
              NodoAST RESULT =null;
		int whilesleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int whilesright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST whiles = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = whiles; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= IF_SENTENCIA 
            {
              NodoAST RESULT =null;
		int ifsleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int ifsright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST ifs = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = ifs; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= RETORNO 
            {
              NodoAST RESULT =null;
		int retleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int retright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST ret = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = ret; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= ASIGNACION 
            {
              NodoAST RESULT =null;
		int asigleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int asigright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST asig = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = asig; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= DECLARACION 
            {
              NodoAST RESULT =null;
		int decleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int decright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST dec = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = dec; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTA_SENTENCIAS ::= LISTA_SENTENCIAS SENTENCIA 
            {
              List<NodoAST> RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		List<NodoAST> lista = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int sentencialeft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int sentenciaright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		NodoAST sentencia = (NodoAST)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 
            lista.add((NodoAST)sentencia);
            RESULT = lista;
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTA_SENTENCIAS ::= 
            {
              List<NodoAST> RESULT =null;
		 RESULT = new ArrayList<NodoAST>(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= Bool Main ParentesisAbre ParentesisCierra LlaveAbre LISTA_SENTENCIAS LlaveCierra 
            {
              NodoPrograma RESULT =null;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).right;
		Object tipoRetorno = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		int sentenciasleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int sentenciasright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		List<NodoAST> sentencias = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            List<NodoAST> lista = (sentencias == null) ? new ArrayList<>() : (List<NodoAST>)sentencias;
            RESULT = new NodoPrograma(tipoRetorno.toString(), lista);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= Void Main ParentesisAbre ParentesisCierra LlaveAbre LISTA_SENTENCIAS LlaveCierra 
            {
              NodoPrograma RESULT =null;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).right;
		Object tipoRetorno = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		int sentenciasleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int sentenciasright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		List<NodoAST> sentencias = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            List<NodoAST> lista = (sentencias == null) ? new ArrayList<>() : (List<NodoAST>)sentencias;
            RESULT = new NodoPrograma(tipoRetorno.toString(), lista);
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= Int Main ParentesisAbre ParentesisCierra LlaveAbre LISTA_SENTENCIAS LlaveCierra 
            {
              NodoPrograma RESULT =null;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).right;
		Object tipoRetorno = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		int sentenciasleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int sentenciasright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		List<NodoAST> sentencias = (List<NodoAST>)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 
            List<NodoAST> lista = (sentencias == null) ? new ArrayList<>() : (List<NodoAST>)sentencias;
            RESULT = new NodoPrograma(tipoRetorno.toString(), lista); 
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		NodoPrograma start_val = (NodoPrograma)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

