
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 28 02:09:10 ART 2025
//----------------------------------------------------

package AnalizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 23;
  public static final int ParentesisCierra = 15;
  public static final int ParentesisAbre = 14;
  public static final int Then = 22;
  public static final int Suma = 10;
  public static final int Numero = 20;
  public static final int Var = 32;
  public static final int Mayor = 28;
  public static final int True = 7;
  public static final int And = 25;
  public static final int LlaveCierra = 18;
  public static final int Identificador = 19;
  public static final int UMENOS = 33;
  public static final int Int = 2;
  public static final int False = 8;
  public static final int PuntoYComa = 16;
  public static final int Not = 27;
  public static final int Or = 26;
  public static final int Main = 5;
  public static final int EOF = 0;
  public static final int LlaveAbre = 17;
  public static final int IgualIgual = 30;
  public static final int Division = 13;
  public static final int If = 21;
  public static final int Resta = 11;
  public static final int Return = 6;
  public static final int error = 1;
  public static final int Bool = 3;
  public static final int Menor = 29;
  public static final int Modulo = 31;
  public static final int Void = 4;
  public static final int Igual = 9;
  public static final int While = 24;
  public static final int Multiplicacion = 12;
}

